modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"
issueTrackerURL="https://github.com/onVoid/Quark-Azalea/issues"


[[mods]]
modId="quarkazalea"
version="${file.jarVersion}"
displayName="Better Quark Azalea"
displayURL="https://www.curseforge.com/minecraft/mc-mods/better-quark-azalea"
updateJSONURL="https://onvoid.net/quarkazalea/update.json"
logoFile="quarkazalea.png"
logoBlur=false
credits="SameDifferent, foquito_azul, Vazkii"
authors="onVoid"
description="Adds block variants from Quark for Better Azalea's wood types (and crafting tables)."
itemIcon="quarkazalea:azalea_chest"
configBackground="azalea:textures/block/azalea_planks.png"

[[dependencies.quarkazalea]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.quarkazalea]]
    modId="azalea"
    mandatory=true
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.quarkazalea]]
    modId="blueprint"
    mandatory=true
    versionRange="[0,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.quarkazalea]]
    modId="quark"
    mandatory=true
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"